In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [7]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [11]:
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [15]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3:2])
print(a[0::2])
print(a[1::])
print(a[2:2:])
print(a[:2:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[]
[[1 2 3 4]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [2]:
reversed_array=arr[::-1]
print(reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [4]:
row1=arr[0,:]
print(row1)

[1 2 3]
