In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
import numpy as np
b=np.array([[1,2,3,4,],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
d=np.random.random((3,2))
print(d)

[[0.90552975 0.37404212]
 [0.03689552 0.80639498]
 [0.04172794 0.72071966]]


In [6]:
e=np.arange(0,25,5)
print(e)

[ 0  5 10 15 20]


In [1]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [2]:
import numpy as np
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [3]:
print(arr.ndim)

2


In [4]:
print(arr.shape)

(3, 4)


In [5]:
print(arr.dtype)

int64


In [6]:
print(arr.size)

12


In [7]:
newtype=arr.astype('f')
print("\n Convert array:\n",newtype)
print("\n Cnverted array type:\n",newtype.dtype)


 Convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 Cnverted array type:
 float32


In [8]:
size=len(arr)
print("\n Size of the array:\n",size)


 Size of the array:
 3
