In [1]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==4)
print(x)

(array([5], dtype=int64),)


In [15]:
arr=np.array([1,6,2,7,6,4])
x1=np.array(arr%2==0)
print(x1)

[False  True  True False  True  True]


In [19]:
arr=np.array([1,6,2,7,6,4])
x2=np.array(arr%2==0)
print(x2)

[False  True  True False  True  True]


In [29]:
#sorting with respect to index
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,3,side='left')
print(x)

4


In [25]:
arr=np.array([0,1,5,3,6,7,2])
x=np.searchsorted(arr,3,side='left')
print(x)

2


In [27]:
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [31]:
#sorting of an array
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [33]:
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [37]:
#filtering
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
narr=arr>42
newarr=arr[narr]
print(arr)
print(x)
print(narr)
print(newarr)

[41 42 43 44]
[True, False, True, False]
[False False  True  True]
[43 44]


In [43]:
arr=np.array([31,78,69,88])
x1=[False,True,True,False]
newarr=arr[x1]
print(x1)
print(newarr)

[False, True, True, False]
[78 69]
